CREATE TABLE recipe_ingredients (
    recipe_ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id            BIGINT NOT NULL,
    ingredient_id        BIGINT NOT NULL,
    quantity             REAL NOT NULL,
    unit_of_measure_id   BIGINT,
    display_order        INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_recipe_ingredients_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredients_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id),
    CONSTRAINT fk_recipe_ingredients_unit
        FOREIGN KEY (unit_of_measure_id) REFERENCES units_of_measure (unit_id)
);

CREATE INDEX idx_recipe_ingredients_recipe_order
    ON recipe_ingredients (recipe_id, display_order);