CREATE TABLE meal_types (
    meal_type_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id       BIGINT,
    name                VARCHAR(120) NOT NULL,
    is_system           BOOLEAN NOT NULL DEFAULT FALSE,
    default_sort_order  INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_meal_types_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id),
    CONSTRAINT chk_meal_types_system_owner
        CHECK (
            (is_system = TRUE AND owner_user_id IS NULL)
            OR (is_system = FALSE AND owner_user_id IS NOT NULL)
        )
);

-- System names unique (case-insensitive)
CREATE UNIQUE INDEX uk_meal_types_system_name_lower
    ON meal_types (LOWER(name))
    WHERE owner_user_id IS NULL;

-- Custom names unique per user (case-insensitive)
CREATE UNIQUE INDEX uk_meal_types_owner_name_lower
    ON meal_types (owner_user_id, LOWER(name))
    WHERE owner_user_id IS NOT NULL;

CREATE INDEX idx_meal_types_owner ON meal_types (owner_user_id);

INSERT INTO meal_types (owner_user_id, name, is_system, default_sort_order) VALUES
    (NULL, 'Desayuno', TRUE, 1),
    (NULL, 'Comida',   TRUE, 2),
    (NULL, 'Cena',     TRUE, 3);