CREATE TABLE calendar_entries (
    calendar_entry_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id       BIGINT NOT NULL,
    recipe_id           BIGINT NOT NULL,
    meal_type_id        BIGINT NOT NULL,
    plan_date           DATE NOT NULL,
    recipe_sort_order   INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_calendar_entries_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_calendar_entries_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT fk_calendar_entries_meal_type
        FOREIGN KEY (meal_type_id) REFERENCES meal_types (meal_type_id)
);

CREATE INDEX idx_calendar_entries_owner_plan_date
    ON calendar_entries (owner_user_id, plan_date);

CREATE INDEX idx_calendar_entries_owner_date_meal
    ON calendar_entries (owner_user_id, plan_date, meal_type_id);