CREATE TABLE day_meal_layout (
    day_meal_layout_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id       BIGINT NOT NULL,
    plan_date           DATE NOT NULL,
    meal_type_id        BIGINT NOT NULL,
    meal_sort_order     INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_day_meal_layout_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_day_meal_layout_meal_type
        FOREIGN KEY (meal_type_id) REFERENCES meal_types (meal_type_id),
    CONSTRAINT uk_day_meal_layout_owner_date_meal
        UNIQUE (owner_user_id, plan_date, meal_type_id)
);

CREATE INDEX idx_day_meal_layout_owner_date
    ON day_meal_layout (owner_user_id, plan_date);