-- Initial schema (English, snake_case). Matches JPA entities.

CREATE TABLE users (
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255),
    last_name VARCHAR(255),
    username  VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    verified  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE ingredient_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    CONSTRAINT uk_ingredient_categories_name UNIQUE (name)
);

CREATE TABLE units_of_measure (
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    symbol  VARCHAR(20),
    CONSTRAINT uk_units_of_measure_name UNIQUE (name)
);

CREATE TABLE ingredients (
    ingredient_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    category_id    BIGINT,
    owner_user_id  BIGINT,
    CONSTRAINT fk_ingredients_category
        FOREIGN KEY (category_id) REFERENCES ingredient_categories (category_id),
    CONSTRAINT fk_ingredients_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id)
);

CREATE TABLE shopping_list_items (
    shopping_list_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    ingredient_id         BIGINT NOT NULL,
    bought                BOOLEAN NOT NULL,
    quantity              REAL NOT NULL,
    unit_of_measure_id    BIGINT,
    CONSTRAINT fk_shopping_list_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_shopping_list_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id),
    CONSTRAINT fk_shopping_list_unit
        FOREIGN KEY (unit_of_measure_id) REFERENCES units_of_measure (unit_id)
);

CREATE INDEX idx_shopping_list_items_user_id ON shopping_list_items (user_id);

-- Prevent duplicate global names (owner_user_id IS NULL)
CREATE UNIQUE INDEX uk_ingredients_catalog_name_lower ON ingredients (LOWER(name))
    WHERE owner_user_id IS NULL;

-- Prevent duplicate names per user (owner_user_id IS NOT NULL)
CREATE UNIQUE INDEX uk_ingredients_user_name_lower ON ingredients (owner_user_id, LOWER(name))
    WHERE owner_user_id IS NOT NULL;
