CREATE TABLE recent_ingredients (
    recent_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    ingredient_id  BIGINT NOT NULL,
    last_used_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usage_count    INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_recent_user
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_recent_ingredient
        FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id),
    CONSTRAINT uk_recent_user_ingredient UNIQUE (user_id, ingredient_id)
);

CREATE INDEX idx_recent_user_last_used
    ON recent_ingredients (user_id, last_used_at DESC);