CREATE TABLE recipe_categories (
    category_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id   BIGINT NOT NULL,
    name            VARCHAR(120) NOT NULL,
    CONSTRAINT fk_recipe_categories_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id),
    CONSTRAINT uk_recipe_categories_owner_name UNIQUE (owner_user_id, name)
);

CREATE INDEX idx_recipe_categories_owner ON recipe_categories (owner_user_id);