CREATE TABLE recipe_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    CONSTRAINT uk_recipe_categories_name UNIQUE (name)
);

INSERT INTO recipe_categories (name)
VALUES ('Sin categoría')
ON CONFLICT (name) DO NOTHING;