CREATE TABLE recipes (
    recipe_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id    BIGINT NOT NULL,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipes_owner
        FOREIGN KEY (owner_user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_recipes_owner ON recipes (owner_user_id);

CREATE TABLE recipe_category_links (
    recipe_id    BIGINT NOT NULL,
    category_id  BIGINT NOT NULL,
    PRIMARY KEY (recipe_id, category_id),
    CONSTRAINT fk_recipe_category_links_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_category_links_category
        FOREIGN KEY (category_id) REFERENCES recipe_categories (category_id) ON DELETE CASCADE
);