-- Steps and media (global recipe or associated to a step).

CREATE TABLE recipe_steps (
    step_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id   BIGINT NOT NULL,
    step_number INT NOT NULL,
    content     TEXT NOT NULL,
    CONSTRAINT fk_recipe_steps_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT uk_recipe_steps_recipe_number UNIQUE (recipe_id, step_number)
);

CREATE INDEX idx_recipe_steps_recipe ON recipe_steps (recipe_id);

CREATE TABLE recipe_media (
    media_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id         BIGINT NOT NULL,
    recipe_step_id    BIGINT,
    relative_path     VARCHAR(512) NOT NULL,
    content_type      VARCHAR(255) NOT NULL,
    original_filename VARCHAR(255),
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipe_media_recipe
        FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_media_step
        FOREIGN KEY (recipe_step_id) REFERENCES recipe_steps (step_id) ON DELETE CASCADE
);

CREATE INDEX idx_recipe_media_recipe ON recipe_media (recipe_id);
CREATE INDEX idx_recipe_media_step ON recipe_media (recipe_step_id);